language: c++

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8.3

addons:
  apt:
    packages:
      - libsdl1.2-dev 
      - libgtk2.0-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl     ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gtk+    ; fi

script:
  - cd BasiliskII/src/Unix
  - NO_CONFIGURE=1 ./autogen.sh
  - ./configure --enable-sdl-video --enable-sdl-audio --disable-vosf --disable-jit-compiler --with-x --with-gtk --with-mon
  - make -j 4
