# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/xenial32"
  config.ssh.forward_x11 = true
  config.ssh.forward_agent = true
  # TODO: define your own shared folder for VM.
  # Leave your ROM and Image in host.
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  config.vm.synced_folder "/Users/Ricky/repo/68K.Mac/BasilikII", "/BasiliskII", type: "virtualbox"
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true

    # Customize the amount of memory on the VM:
    vb.memory = "1024"

    vb.cpus = "2"
  end
  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get install build-essential git automake libsdl1.2-dev libgtk2.0-dev -y
    sudo apt-get install xfce4 -y
    echo -e "ubuntu\nubuntu" | sudo passwd ubuntu
  SHELL

  $script = <<-SCRIPT
  git clone https://github.com/rickyzhang82/macemu.git
  cd macemu/BasiliskII/src/Unix
  NO_CONFIGURE=1 ./autogen.sh
  ./configure --enable-sdl-video --enable-sdl-audio --disable-vosf --enable-jit-compiler --with-x
  make
  cd Linux/NetDriver/
  make -j 2
  sudo make dev
  sudo make install
  sudo modprobe sheep_net
  sudo chown vagrant:vagrant /dev/sheep_net
  SCRIPT
  config.vm.provision "shell", inline: $script, privileged: false

end
